# Netlify config file
# https://docs.netlify.com/configure-builds/file-based-configuration/
[build]
  command = "npm run build"
  publish = "public"
[build.environment]
    # do not show Cypress installation progress messages
    CI = "1"
    # cache Cypress binary in local "node_modules" folder
    # so Netlify caches it
    CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
    # set TERM variable for terminal output
    TERM = "xterm"

[[plugins]]
  package = "netlify-plugin-cypress"
  # let's first test the site before Gatsby builds it
  [plugins.inputs.preBuild]
    start = 'npm run develop'
    wait-on = 'http://localhost:8000'
    wait-on-timeout = '30' # seconds
    record = true
    group = '1: testing develop site'
    # tag = 'pre-build'
  # then Netlify builds the site
  # and then our tests will run again, testing the built production version
  [plugins.inputs]
  record = true
  group = '2: testing built site'
  # tag = 'post-build'
